In [19]:
import pandas as pd
import numpy as np

In [37]:
try:
    trades_raw = pd.read_csv('./trades.csv')
except FileNotFoundError as error:
    print(f"File not found: {error}")

In [5]:
'''list first 5 rows'''
trades_raw.head(5)

   trade_id instrument   price  volume  trade_date
0        26       AAPL  186.54    1688  2026-04-13
1        31       AAPL  180.50    2154  2026-04-27
2        44       AAPL  182.73    2401  2026-06-07
3         8       AAPL  186.84    1778  2026-02-11
4        35       AAPL  181.57     447  2026-05-05

In [ ]:
'''set trade_id to index'''
# trades_raw.index = trades_raw['trade_id']

In [6]:
'''
lock onto specific rows. 
loc[rows, columns]
'''
trades_raw.loc[0:5, ['instrument', 'price']]

  instrument   price
0       AAPL  186.54
1       AAPL  180.50
2       AAPL  182.73
3       AAPL  186.84
4       AAPL  181.57
5       AAPL  181.26

In [7]:
trades_raw.iloc[0:5, [0, 2]]

   trade_id   price
0        26  186.54
1        31  180.50
2        44  182.73
3         8  186.84
4        35  181.57

Accessing Data with Pandas

In [8]:
trades_raw.sort_values("volume", ascending=False)

     trade_id instrument   price  volume  trade_date
222       145       TSLA  183.60    2493  2026-05-23
208       125       TSLA  180.98    2486  2026-03-10
185        82       MSFT  398.00    2480  2026-04-18
146       159      GOOGL  167.98    2467  2026-01-16
30         27       AAPL  184.24    2444  2026-04-15
..        ...        ...     ...     ...         ...
4          35       AAPL  181.57     447  2026-05-05
158        57       MSFT  413.36     429  2026-01-14
24         40       AAPL  180.77     413  2026-05-17
38         43       AAPL  181.94     402  2026-06-06
214       141       TSLA  184.60     401  2026-05-10

[253 rows x 5 columns]

In [ ]:
for index, row in trades_raw.iterrows():
    print(index, row["price"])

Filter Data

In [38]:
# introduce missing values
trades_raw.loc[trades_raw.index[3], 'price'] = None
trades_raw.loc[trades_raw.index[10], 'volume'] = None

# introduce a duplicate row
dupe = trades_raw.loc[[trades_raw.index[5]]]
data = pd.concat([trades_raw, dupe])

In [39]:
trades_raw.head()

   trade_id instrument   price  volume  trade_date
0        26       AAPL  186.54  1688.0  2026-04-13
1        31       AAPL  180.50  2154.0  2026-04-27
2        44       AAPL  182.73  2401.0  2026-06-07
3         8       AAPL     NaN  1778.0  2026-02-11
4        35       AAPL  181.57   447.0  2026-05-05

In [40]:
trades_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   trade_id    253 non-null    int64
 1   instrument  253 non-null    str
 2   price       252 non-null    float64
 3   volume      252 non-null    float64
 4   trade_date  253 non-null    str
dtypes: float64(2), int64(1), str(2)
memory usage: 10.0 KB

In [41]:
trades_raw[trades_raw['price'].isna()]

   trade_id instrument  price  volume  trade_date
3         8       AAPL    NaN  1778.0  2026-02-11

In [42]:
trades_raw[(trades_raw["volume"] > 2000) & (trades_raw["instrument"] == "AAPL" )]

    trade_id instrument   price  volume  trade_date
1         31       AAPL  180.50  2154.0  2026-04-27
2         44       AAPL  182.73  2401.0  2026-06-07
6         24       AAPL  185.09  2043.0  2026-04-09
17        51       AAPL  179.11  2346.0  2026-06-26
18        16       AAPL  183.53  2257.0  2026-03-12
28         5       AAPL  187.20  2118.0  2026-01-24
30        27       AAPL  184.24  2444.0  2026-04-15
32        28       AAPL  183.41  2279.0  2026-04-18
37        49       AAPL  179.55  2390.0  2026-06-24
43        39       AAPL  183.50  2180.0  2026-05-16
44        34       AAPL  181.34  2317.0  2026-05-04
45        32       AAPL  181.52  2129.0  2026-05-02

In [43]:
data[(data['instrument'].str.contains("TSLA|AAPL")) & (data["volume"] > 2000)].sort_values("volume", ascending=False)

     trade_id instrument   price  volume  trade_date
222       145       TSLA  183.60  2493.0  2026-05-23
208       125       TSLA  180.98  2486.0  2026-03-10
30         27       AAPL  184.24  2444.0  2026-04-15
2          44       AAPL  182.73  2401.0  2026-06-07
37         49       AAPL  179.55  2390.0  2026-06-24
17         51       AAPL  179.11  2346.0  2026-06-26
44         34       AAPL  181.34  2317.0  2026-05-04
32         28       AAPL  183.41  2279.0  2026-04-18
18         16       AAPL  183.53  2257.0  2026-03-12
245       144       TSLA  182.19  2211.0  2026-05-18
249       106       TSLA  174.46  2209.0  2026-01-02
230       132       TSLA  181.69  2186.0  2026-04-11
43         39       AAPL  183.50  2180.0  2026-05-16
226       130       TSLA  180.45  2179.0  2026-03-28
1          31       AAPL  180.50  2154.0  2026-04-27
233       107       TSLA  174.87  2151.0  2026-01-03
45         32       AAPL  181.52  2129.0  2026-05-02
28          5       AAPL  187.20  2118.0  2026-01-24
209       119       TSLA  181.74  2086.0  2026-02-20
228       138       TSLA  183.01  2072.0  2026-04-26
6          24       AAPL  185.09  2043.0  2026-04-09

In [16]:
trades_raw.query('instrument == "AAPL" and volume > 2000').sort_values("trade_date", ascending=False)

    trade_id instrument   price  volume  trade_date
17        51       AAPL  179.11  2346.0  2026-06-26
37        49       AAPL  179.55  2390.0  2026-06-24
2         44       AAPL  182.73  2401.0  2026-06-07
43        39       AAPL  183.50  2180.0  2026-05-16
44        34       AAPL  181.34  2317.0  2026-05-04
45        32       AAPL  181.52  2129.0  2026-05-02
1         31       AAPL  180.50  2154.0  2026-04-27
32        28       AAPL  183.41  2279.0  2026-04-18
30        27       AAPL  184.24  2444.0  2026-04-15
6         24       AAPL  185.09  2043.0  2026-04-09
18        16       AAPL  183.53  2257.0  2026-03-12
28         5       AAPL  187.20  2118.0  2026-01-24

In [44]:
trades_raw["trade_date"] = pd.to_datetime(trades_raw['trade_date'])

In [46]:
trades_raw.head()

   trade_id instrument   price  volume trade_date
0        26       AAPL  186.54  1688.0 2026-04-13
1        31       AAPL  180.50  2154.0 2026-04-27
2        44       AAPL  182.73  2401.0 2026-06-07
3         8       AAPL     NaN  1778.0 2026-02-11
4        35       AAPL  181.57   447.0 2026-05-05

In [48]:
trades_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   trade_id    253 non-null    int64
 1   instrument  253 non-null    str
 2   price       252 non-null    float64
 3   volume      252 non-null    float64
 4   trade_date  253 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 10.0 KB

In [49]:
trades_raw["trade_month"] = trades_raw["trade_date"].dt.month
trades_raw["trade_year"] = trades_raw["trade_date"].dt.year

In [50]:
trades_raw

     trade_id instrument   price  volume trade_date  trade_month  trade_year
0          26       AAPL  186.54  1688.0 2026-04-13            4        2026
1          31       AAPL  180.50  2154.0 2026-04-27            4        2026
2          44       AAPL  182.73  2401.0 2026-06-07            6        2026
3           8       AAPL     NaN  1778.0 2026-02-11            2        2026
4          35       AAPL  181.57   447.0 2026-05-05            5        2026
..        ...        ...     ...     ...        ...          ...         ...
248       124       TSLA  182.17  1543.0 2026-03-08            3        2026
249       106       TSLA  174.46  2209.0 2026-01-02            1        2026
250       112       TSLA  172.42   571.0 2026-01-21            1        2026
251       129       TSLA  184.14  1487.0 2026-03-25            3        2026
252       148       TSLA  181.52  1320.0 2026-06-11            6        2026

[253 rows x 7 columns]

In [51]:
trades_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   trade_id     253 non-null    int64
 1   instrument   253 non-null    str
 2   price        252 non-null    float64
 3   volume       252 non-null    float64
 4   trade_date   253 non-null    datetime64[us]
 5   trade_month  253 non-null    int32
 6   trade_year   253 non-null    int32
dtypes: datetime64[us](1), float64(2), int32(2), int64(1), str(1)
memory usage: 12.0 KB

In [52]:
#case statement in sql
trades_raw["trade_size"] = trades_raw["volume"].apply(lambda x: 'large' if x > 1500 else 'short')

In [53]:
trades_raw

,trade_id,instrument,price,volume,trade_date,trade_month,trade_year,trade_size
0,26,AAPL,186.54,1688.0,2026-04-13,4,2026,large
1,31,AAPL,180.50,2154.0,2026-04-27,4,2026,large
2,44,AAPL,182.73,2401.0,2026-06-07,6,2026,large
3,8,AAPL,NaN,1778.0,2026-02-11,2,2026,large
4,35,AAPL,181.57,447.0,2026-05-05,5,2026,short
...,...,...,...,...,...,...,...,...
248,124,TSLA,182.17,1543.0,2026-03-08,3,2026,large
249,106,TSLA,174.46,2209.0,2026-01-02,1,2026,large
250,112,TSLA,172.42,571.0,2026-01-21,1,2026,short
251,129,TSLA,184.14,1487.0,2026-03-25,3,2026,short
252,148,TSLA,181.52,1320.0,2026-06-11,6,2026,short

In [54]:
trades_raw.query('price > 186')

,trade_id,instrument,price,volume,trade_date,trade_month,trade_year,trade_size
0,26,AAPL,186.54,1688.0,2026-04-13,4,2026,large
7,38,AAPL,186.61,1793.0,2026-05-13,5,2026,large
9,3,AAPL,188.85,1295.0,2026-01-08,1,2026,short
14,1,AAPL,191.89,756.0,2026-01-01,1,2026,short
23,2,AAPL,192.61,530.0,2026-01-05,1,2026,short
...,...,...,...,...,...,...,...,...
201,54,MSFT,415.43,1320.0,2026-01-09,1,2026,short
202,63,MSFT,409.96,2165.0,2026-02-07,2,2026,large
203,75,MSFT,412.45,1074.0,2026-03-08,3,2026,short
204,103,MSFT,393.49,1233.0,2026-06-21,6,2026,short
207,128,TSLA,186.71,1469.0,2026-03-16,3,2026,short

In [65]:
trades_raw.isna().sum()

trade_id       0
instrument     0
price          1
volume         1
trade_date     0
trade_month    0
trade_year     0
trade_size     0
dtype: int64

In [66]:
trades_raw = trades_raw.sort_values(["instrument", "trade_date"])
trades_raw["price"] = trades_raw.groupby("instrument")["price"].transform(lambda x: x.interpolate())
trades_raw["volume"] = trades_raw["volume"].fillna(trades_raw["volume"].mean())

In [67]:
trades_raw.isna().sum()

trade_id       0
instrument     0
price          0
volume         0
trade_date     0
trade_month    0
trade_year     0
trade_size     0
dtype: int64

In [68]:
trades_raw

,trade_id,instrument,price,volume,trade_date,trade_month,trade_year,trade_size
14,1,AAPL,191.89,756.0,2026-01-01,1,2026,short
23,2,AAPL,192.61,530.0,2026-01-05,1,2026,short
9,3,AAPL,188.85,1295.0,2026-01-08,1,2026,short
35,4,AAPL,186.71,508.0,2026-01-09,1,2026,short
28,5,AAPL,187.20,2118.0,2026-01-24,1,2026,large
...,...,...,...,...,...,...,...,...
252,148,TSLA,181.52,1320.0,2026-06-11,6,2026,short
232,149,TSLA,183.97,1003.0,2026-06-17,6,2026,short
212,150,TSLA,180.17,1402.0,2026-06-20,6,2026,short
206,151,TSLA,184.04,698.0,2026-06-21,6,2026,short
210,152,TSLA,183.68,1196.0,2026-06-22,6,2026,short

In [78]:
trades_raw.groupby(['instrument', 'trade_year', 'trade_month']).agg({
    'volume': 'sum',
    'price': 'mean'
})

                                         volume       price
instrument trade_year trade_month
AAPL       2026       1             6746.000000  188.703333
                      2             8477.869048  182.508333
                      3            12163.000000  182.063333
                      4            15479.000000  182.955000
                      5            15094.000000  182.947000
                      6            15168.000000  181.054000
AMZN       2026       1            13893.000000  185.377500
                      2            13376.000000  187.508750
                      3            15543.000000  184.893333
                      4             9975.000000  174.610000
                      5            14080.000000  166.682222
                      6            15643.000000  156.169000
GOOGL      2026       1            17870.000000  164.781111
                      2            11409.000000  169.373333
                      3            10731.000000  165.710000
                      4            14058.000000  166.717778
                      5             8126.000000  162.741250
                      6            10300.000000  158.400000
MSFT       2026       1            11154.000000  412.988000
                      2            11640.000000  408.831111
                      3            15603.000000  409.498889
                      4            10486.000000  395.900000
                      5            12886.000000  390.266000
                      6             9250.000000  391.936250
TSLA       2026       1            13012.000000  173.651000
                      2             9099.000000  180.685714
                      3            14524.000000  181.961111
                      4            11621.000000  180.875000
                      5            11923.000000  183.632500
                      6             6981.000000  182.253333

In [82]:
trades_raw[trades_raw['instrument'].isin(['TSLA', 'AAPL'])].groupby(['instrument', 'trade_year', 'trade_month']).agg({
    'volume': 'sum',
    'price': 'mean'
}).round(2)

                                     volume   price
instrument trade_year trade_month
AAPL       2026       1             6746.00  188.70
                      2             8477.87  182.51
                      3            12163.00  182.06
                      4            15479.00  182.96
                      5            15094.00  182.95
                      6            15168.00  181.05
TSLA       2026       1            13012.00  173.65
                      2             9099.00  180.69
                      3            14524.00  181.96
                      4            11621.00  180.88
                      5            11923.00  183.63
                      6             6981.00  182.25