In [1]:
import pandas as pd
import numpy as np

In [128]:
raw_trades = pd.read_csv('/Users/mryiadom/aws-de-portfolio/data/raw_trades.csv')

In [129]:
raw_trades.head()

,trade_id,instrument_id,ticker,sector,trade_date,price,volume,venue_code,side
0,1001,1,AAPL,Technology,2026-01-15,NaN,2500.0,XNAS,SELL
1,1002,1,AAPL,Technology,2026-01-08,NaN,1000.0,XNAS,BUY
2,1003,1,AAPL,Technology,2026-02-09,219.86,7500.0,XNAS,BUY
3,1004,1,AAPL,Technology,2026-02-16,215.86,2000.0,XNAS,SELL
4,1005,1,AAPL,Technology,2026-03-13,209.18,1500.0,XNAS,SELL

In [130]:
raw_trades.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   trade_id       56 non-null     int64
 1   instrument_id  56 non-null     int64
 2   ticker         56 non-null     str
 3   sector         56 non-null     str
 4   trade_date     56 non-null     str
 5   price          50 non-null     float64
 6   volume         53 non-null     float64
 7   venue_code     56 non-null     str
 8   side           56 non-null     str
dtypes: float64(2), int64(2), str(5)
memory usage: 4.1 KB

In [131]:
raw_trades.shape

(56, 9)

In [132]:
raw_trades.dtypes

trade_id           int64
instrument_id      int64
ticker               str
sector               str
trade_date           str
price            float64
volume           float64
venue_code           str
side                 str
dtype: object

In [133]:
raw_trades['volume'] = raw_trades['volume'].astype('Int64')
raw_trades['trade_date'] = pd.to_datetime(raw_trades['trade_date'])

In [134]:
raw_trades.dtypes

trade_id                  int64
instrument_id             int64
ticker                      str
sector                      str
trade_date       datetime64[us]
price                   float64
volume                    Int64
venue_code                  str
side                        str
dtype: object

In [135]:
raw_trades.isna().sum()

trade_id         0
instrument_id    0
ticker           0
sector           0
trade_date       0
price            6
volume           3
venue_code       0
side             0
dtype: int64

In [136]:
raw_trades.set_index('trade_date', inplace=True)
raw_trades.sort_index(ascending=True, inplace=True)

In [137]:
raw_trades.head()

,trade_id,instrument_id,ticker,sector,price,volume,venue_code,side
trade_date,,,,,,,,
2026-01-03,1044,5,JNJ,Healthcare,160.04,1000,XNYS,SELL
2026-01-03,1045,5,JNJ,Healthcare,152.56,7500,XNYS,SELL
2026-01-07,1012,2,MSFT,Technology,438.92,1500,XNAS,SELL
2026-01-08,1002,1,AAPL,Technology,NaN,1000,XNAS,BUY
2026-01-11,1013,2,MSFT,Technology,447.60,7500,XNAS,BUY

In [138]:
raw_trades['trade_month'] = raw_trades.index.month
raw_trades['trade_year'] = raw_trades.index.year

In [139]:
raw_trades.head()

,trade_id,instrument_id,ticker,sector,price,volume,venue_code,side,trade_month,trade_year
trade_date,,,,,,,,,,
2026-01-03,1044,5,JNJ,Healthcare,160.04,1000,XNYS,SELL,1,2026
2026-01-03,1045,5,JNJ,Healthcare,152.56,7500,XNYS,SELL,1,2026
2026-01-07,1012,2,MSFT,Technology,438.92,1500,XNAS,SELL,1,2026
2026-01-08,1002,1,AAPL,Technology,NaN,1000,XNAS,BUY,1,2026
2026-01-11,1013,2,MSFT,Technology,447.60,7500,XNAS,BUY,1,2026

In [140]:
raw_trades.query('trade_month == 1')

,trade_id,instrument_id,ticker,sector,price,volume,venue_code,side,trade_month,trade_year
trade_date,,,,,,,,,,
2026-01-03,1044,5,JNJ,Healthcare,160.04,1000,XNYS,SELL,1,2026
2026-01-03,1045,5,JNJ,Healthcare,152.56,7500,XNYS,SELL,1,2026
2026-01-07,1012,2,MSFT,Technology,438.92,1500,XNAS,SELL,1,2026
2026-01-08,1002,1,AAPL,Technology,NaN,1000,XNAS,BUY,1,2026
2026-01-11,1013,2,MSFT,Technology,447.60,7500,XNAS,BUY,1,2026
2026-01-13,1023,3,JPM,Financials,201.75,750,XNYS,BUY,1,2026
2026-01-13,1023,3,JPM,Financials,201.75,750,XNYS,BUY,1,2026
2026-01-15,1001,1,AAPL,Technology,NaN,2500,XNAS,SELL,1,2026
2026-01-17,1024,3,JPM,Financials,206.01,750,XNYS,SELL,1,2026
2026-01-27,1034,4,XOM,Energy,124.22,1000,XNYS,BUY,1,2026

In [141]:
raw_trades[raw_trades['trade_month'] == 1]

,trade_id,instrument_id,ticker,sector,price,volume,venue_code,side,trade_month,trade_year
trade_date,,,,,,,,,,
2026-01-03,1044,5,JNJ,Healthcare,160.04,1000,XNYS,SELL,1,2026
2026-01-03,1045,5,JNJ,Healthcare,152.56,7500,XNYS,SELL,1,2026
2026-01-07,1012,2,MSFT,Technology,438.92,1500,XNAS,SELL,1,2026
2026-01-08,1002,1,AAPL,Technology,NaN,1000,XNAS,BUY,1,2026
2026-01-11,1013,2,MSFT,Technology,447.60,7500,XNAS,BUY,1,2026
2026-01-13,1023,3,JPM,Financials,201.75,750,XNYS,BUY,1,2026
2026-01-13,1023,3,JPM,Financials,201.75,750,XNYS,BUY,1,2026
2026-01-15,1001,1,AAPL,Technology,NaN,2500,XNAS,SELL,1,2026
2026-01-17,1024,3,JPM,Financials,206.01,750,XNYS,SELL,1,2026
2026-01-27,1034,4,XOM,Energy,124.22,1000,XNYS,BUY,1,2026

In [142]:
raw_trades.loc[raw_trades['trade_month'] == 1, ["ticker", "price"]]

           ticker   price
trade_date
2026-01-03    JNJ  160.04
2026-01-03    JNJ  152.56
2026-01-07   MSFT  438.92
2026-01-08   AAPL     NaN
2026-01-11   MSFT  447.60
2026-01-13    JPM  201.75
2026-01-13    JPM  201.75
2026-01-15   AAPL     NaN
2026-01-17    JPM  206.01
2026-01-27    XOM  124.22